
definitions = [
    {
        "id": 72,
        "name": "Albania",
        "defaultLanguageId": 3,
        "code": "al",
        "geonameId": 783754,
        "tld": "al",
        "regionId": 5,
        "region": "Europe - Non EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3
        ]
    },
    {
        "id": 50,
        "name": "Algeria",
        "defaultLanguageId": 3,
        "code": "dz",
        "geonameId": 2589581,
        "tld": "dz",
        "regionId": 9,
        "region": "Africa",
        "defaultScanCountryId": 49,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            40,
            4
        ]
    },
    {
        "id": 73,
        "name": "Anguilla",
        "defaultLanguageId": 3,
        "code": "ai",
        "geonameId": 3573511,
        "tld": "ai",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 74,
        "name": "Antigua & Barbuda",
        "defaultLanguageId": 3,
        "code": "ag",
        "geonameId": 3576396,
        "tld": "ag",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 43,
        "name": "Argentina",
        "defaultLanguageId": 24,
        "code": "ar",
        "geonameId": 3865483,
        "tld": "ar",
        "regionId": 6,
        "region": "South America",
        "defaultScanCountryId": 42,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            24
        ]
    },
    {
        "id": 70,
        "name": "Armenia",
        "defaultLanguageId": 53,
        "code": "am",
        "geonameId": 174982,
        "tld": "am",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            53
        ]
    },
    {
        "id": 75,
        "name": "Aruba",
        "defaultLanguageId": 3,
        "code": "aw",
        "geonameId": 3577279,
        "tld": "aw",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 47,
        "name": "Australia",
        "defaultLanguageId": 2,
        "code": "au",
        "geonameId": 2077456,
        "tld": "au",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            2
        ]
    },
    {
        "id": 19,
        "name": "Austria",
        "defaultLanguageId": 47,
        "code": "at",
        "geonameId": 2782113,
        "tld": "at",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            47
        ]
    },
    {
        "id": 76,
        "name": "Bahamas",
        "defaultLanguageId": 3,
        "code": "bs",
        "geonameId": 3572887,
        "tld": "bs",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7,
            3
        ]
    },
    {
        "id": 77,
        "name": "Barbados",
        "defaultLanguageId": 3,
        "code": "bb",
        "geonameId": 3374084,
        "tld": "bb",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7,
            3
        ]
    },
    {
        "id": 144,
        "name": "Belarus",
        "defaultLanguageId": 38,
        "code": "by",
        "geonameId": 630336,
        "tld": "by",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            38
        ]
    },
    {
        "id": 20,
        "name": "Belgium",
        "defaultLanguageId": 22,
        "code": "be",
        "geonameId": 2802361,
        "tld": "be",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            22,
            4
        ]
    },
    {
        "id": 78,
        "name": "Belize",
        "defaultLanguageId": 3,
        "code": "bz",
        "geonameId": 3582678,
        "tld": "bz",
        "regionId": 11,
        "region": "Central America",
        "defaultScanCountryId": 12,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 79,
        "name": "Bermuda",
        "defaultLanguageId": 3,
        "code": "bm",
        "geonameId": 3573345,
        "tld": "bm",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 80,
        "name": "Bolivia",
        "defaultLanguageId": 3,
        "code": "bo",
        "geonameId": 3923057,
        "tld": "bo",
        "regionId": 6,
        "region": "South America",
        "defaultScanCountryId": 42,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 81,
        "name": "Bosnia & Herzegovina",
        "defaultLanguageId": 3,
        "code": "ba",
        "geonameId": 3277605,
        "tld": "ba",
        "regionId": 5,
        "region": "Europe - Non EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            65
        ]
    },
    {
        "id": 42,
        "name": "Brazil",
        "defaultLanguageId": 27,
        "code": "br",
        "geonameId": 3469034,
        "tld": "br",
        "regionId": 6,
        "region": "South America",
        "defaultScanCountryId": 42,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            27
        ]
    },
    {
        "id": 82,
        "name": "British Virgin Islands",
        "defaultLanguageId": 3,
        "code": "vg",
        "geonameId": 3577718,
        "tld": "vg",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 127,
        "name": "Brunei",
        "defaultLanguageId": 3,
        "code": "bn",
        "geonameId": 1820814,
        "tld": "bn",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3
        ]
    },
    {
        "id": 30,
        "name": "Bulgaria",
        "defaultLanguageId": 30,
        "code": "bg",
        "geonameId": 732800,
        "tld": "bg",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            30
        ]
    },
    {
        "id": 123,
        "name": "Cambodia",
        "defaultLanguageId": 3,
        "code": "kh",
        "geonameId": 1831722,
        "tld": "kh",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3
        ]
    },
    {
        "id": 9,
        "name": "Canada",
        "defaultLanguageId": 52,
        "code": "ca",
        "geonameId": 6251999,
        "tld": "ca",
        "regionId": 1,
        "region": "North America",
        "defaultScanCountryId": 1,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            42,
            52,
            3
        ]
    },
    {
        "id": 83,
        "name": "Cayman Islands",
        "defaultLanguageId": 3,
        "code": "ky",
        "geonameId": 3580718,
        "tld": "ky",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7,
            3
        ]
    },
    {
        "id": 84,
        "name": "Chile",
        "defaultLanguageId": 7,
        "code": "cl",
        "geonameId": 3895114,
        "tld": "cl",
        "regionId": 6,
        "region": "South America",
        "defaultScanCountryId": 42,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7
        ]
    },
    {
        "id": 10,
        "name": "China",
        "defaultLanguageId": 43,
        "code": "cn",
        "geonameId": 1814991,
        "tld": "cn",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            43
        ]
    },
    {
        "id": 85,
        "name": "Colombia",
        "defaultLanguageId": 7,
        "code": "co",
        "geonameId": 3686110,
        "tld": "co",
        "regionId": 6,
        "region": "South America",
        "defaultScanCountryId": 42,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7
        ]
    },
    {
        "id": 87,
        "name": "Costa Rica",
        "defaultLanguageId": 3,
        "code": "cr",
        "geonameId": 3624060,
        "tld": "cr",
        "regionId": 11,
        "region": "Central America",
        "defaultScanCountryId": 12,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 61,
        "name": "Croatia",
        "defaultLanguageId": 49,
        "code": "hr",
        "geonameId": 3202326,
        "tld": "hr",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            3,
            49
        ]
    },
    {
        "id": 37,
        "name": "Cyprus",
        "defaultLanguageId": 29,
        "code": "cy",
        "geonameId": 146669,
        "tld": "cy",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            29
        ]
    },
    {
        "id": 27,
        "name": "Czech Republic",
        "defaultLanguageId": 28,
        "code": "cz",
        "geonameId": 3077311,
        "tld": "cz",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            28
        ]
    },
    {
        "id": 88,
        "name": "Democratic Republic of the Congo",
        "defaultLanguageId": 4,
        "code": "cd",
        "geonameId": 203312,
        "tld": "cd",
        "regionId": 9,
        "region": "Africa",
        "defaultScanCountryId": 49,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 15,
        "name": "Denmark",
        "defaultLanguageId": 8,
        "code": "dk",
        "geonameId": 2623032,
        "tld": "dk",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            8
        ]
    },
    {
        "id": 89,
        "name": "Dominica",
        "defaultLanguageId": 3,
        "code": "dm",
        "geonameId": 3575830,
        "tld": "dm",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 90,
        "name": "Dominican Republic",
        "defaultLanguageId": 3,
        "code": "do",
        "geonameId": 3508796,
        "tld": "do",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7,
            3
        ]
    },
    {
        "id": 91,
        "name": "Ecuador",
        "defaultLanguageId": 3,
        "code": "ec",
        "geonameId": 3658394,
        "tld": "ec",
        "regionId": 6,
        "region": "South America",
        "defaultScanCountryId": 42,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7,
            3
        ]
    },
    {
        "id": 40,
        "name": "Egypt",
        "defaultLanguageId": 59,
        "code": "eg",
        "geonameId": 357994,
        "tld": "eg",
        "regionId": 4,
        "region": "Middle East",
        "defaultScanCountryId": 40,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            59,
            40
        ]
    },
    {
        "id": 92,
        "name": "El Salvador",
        "defaultLanguageId": 3,
        "code": "sv",
        "geonameId": 3585968,
        "tld": "sv",
        "regionId": 11,
        "region": "Central America",
        "defaultScanCountryId": 12,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 32,
        "name": "Estonia",
        "defaultLanguageId": 32,
        "code": "ee",
        "geonameId": 453733,
        "tld": "ee",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            32
        ]
    },
    {
        "id": 25,
        "name": "Finland",
        "defaultLanguageId": 25,
        "code": "fi",
        "geonameId": 660013,
        "tld": "fi",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            25
        ]
    },
    {
        "id": 5,
        "name": "France",
        "defaultLanguageId": 4,
        "code": "fr",
        "geonameId": 3017382,
        "tld": "fr",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 135,
        "name": "French Guiana",
        "defaultLanguageId": 4,
        "code": "gf",
        "geonameId": 3381670,
        "tld": "gf",
        "regionId": 6,
        "region": "South America",
        "defaultScanCountryId": 42,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 138,
        "name": "French Polynesia",
        "defaultLanguageId": 4,
        "code": "pf",
        "geonameId": 4030656,
        "tld": "pf",
        "regionId": 7,
        "region": "Other EU",
        "defaultScanCountryId": 5,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 93,
        "name": "Gabon",
        "defaultLanguageId": 4,
        "code": "ga",
        "geonameId": 2400553,
        "tld": "ga",
        "regionId": 9,
        "region": "Africa",
        "defaultScanCountryId": 49,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 120,
        "name": "Georgia",
        "defaultLanguageId": 61,
        "code": "ge",
        "geonameId": 614540,
        "tld": "ge",
        "regionId": 5,
        "region": "Europe - Non EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            61
        ]
    },
    {
        "id": 3,
        "name": "Germany",
        "defaultLanguageId": 5,
        "code": "de",
        "geonameId": 2921044,
        "tld": "de",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            5
        ]
    },
    {
        "id": 141,
        "name": "Gibraltar",
        "defaultLanguageId": 2,
        "code": "gi",
        "geonameId": 2411586,
        "tld": "gi",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            2
        ]
    },
    {
        "id": 29,
        "name": "Greece",
        "defaultLanguageId": 29,
        "code": "gr",
        "geonameId": 390903,
        "tld": "gr",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            29
        ]
    },
    {
        "id": 95,
        "name": "Grenada",
        "defaultLanguageId": 3,
        "code": "gd",
        "geonameId": 3580239,
        "tld": "gd",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 129,
        "name": "Guadeloupe",
        "defaultLanguageId": 4,
        "code": "gp",
        "geonameId": 3579143,
        "tld": "gp",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 96,
        "name": "Guatemala",
        "defaultLanguageId": 3,
        "code": "gt",
        "geonameId": 3595528,
        "tld": "gt",
        "regionId": 11,
        "region": "Central America",
        "defaultScanCountryId": 12,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 131,
        "name": "Guernsey",
        "defaultLanguageId": 2,
        "code": "gg",
        "geonameId": 3042362,
        "tld": "gg",
        "regionId": 7,
        "region": "Other EU",
        "defaultScanCountryId": 5,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            2
        ]
    },
    {
        "id": 97,
        "name": "Guyana",
        "defaultLanguageId": 3,
        "code": "gy",
        "geonameId": 3378535,
        "tld": "gy",
        "regionId": 6,
        "region": "South America",
        "defaultScanCountryId": 42,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 98,
        "name": "Haiti",
        "defaultLanguageId": 3,
        "code": "ht",
        "geonameId": 3723988,
        "tld": "ht",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            4,
            7
        ]
    },
    {
        "id": 99,
        "name": "Honduras",
        "defaultLanguageId": 3,
        "code": "hn",
        "geonameId": 3608932,
        "tld": "hn",
        "regionId": 11,
        "region": "Central America",
        "defaultScanCountryId": 12,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 64,
        "name": "Hong Kong",
        "defaultLanguageId": 44,
        "code": "hk",
        "geonameId": 1819730,
        "tld": "hk",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            44
        ]
    },
    {
        "id": 24,
        "name": "Hungary",
        "defaultLanguageId": 13,
        "code": "hu",
        "geonameId": 719819,
        "tld": "hu",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            13
        ]
    },
    {
        "id": 38,
        "name": "Iceland",
        "defaultLanguageId": 37,
        "code": "is",
        "geonameId": 2629691,
        "tld": "is",
        "regionId": 5,
        "region": "Europe - Non EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            37
        ]
    },
    {
        "id": 59,
        "name": "India",
        "defaultLanguageId": 2,
        "code": "in",
        "geonameId": 1269750,
        "tld": "in",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            2,
            64,
            66
        ]
    },
    {
        "id": 55,
        "name": "Indonesia",
        "defaultLanguageId": 54,
        "code": "id",
        "geonameId": 1643084,
        "tld": "id",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            54
        ]
    },
    {
        "id": 16,
        "name": "Ireland",
        "defaultLanguageId": 2,
        "code": "ie",
        "geonameId": 2963597,
        "tld": "ie",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            2
        ]
    },
    {
        "id": 133,
        "name": "Isle of Man",
        "defaultLanguageId": 2,
        "code": "im",
        "geonameId": 3042225,
        "tld": "im",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            2
        ]
    },
    {
        "id": 11,
        "name": "Israel",
        "defaultLanguageId": 41,
        "code": "il",
        "geonameId": 294640,
        "tld": "il",
        "regionId": 4,
        "region": "Middle East",
        "defaultScanCountryId": 40,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            41
        ]
    },
    {
        "id": 7,
        "name": "Italy",
        "defaultLanguageId": 6,
        "code": "it",
        "geonameId": 3175395,
        "tld": "it",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            6
        ]
    },
    {
        "id": 100,
        "name": "Jamaica",
        "defaultLanguageId": 3,
        "code": "jm",
        "geonameId": 3489940,
        "tld": "jm",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 46,
        "name": "Japan",
        "defaultLanguageId": 46,
        "code": "jp",
        "geonameId": 1861060,
        "tld": "jp",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            46
        ]
    },
    {
        "id": 136,
        "name": "Jersey",
        "defaultLanguageId": 2,
        "code": "je",
        "geonameId": 3042142,
        "tld": "je",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            2
        ]
    },
    {
        "id": 122,
        "name": "Laos",
        "defaultLanguageId": 56,
        "code": "la",
        "geonameId": 1655842,
        "tld": "la",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            56
        ]
    },
    {
        "id": 33,
        "name": "Latvia",
        "defaultLanguageId": 33,
        "code": "lv",
        "geonameId": 458258,
        "tld": "lv",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            33
        ]
    },
    {
        "id": 51,
        "name": "Libya",
        "defaultLanguageId": 3,
        "code": "ly",
        "geonameId": 2215636,
        "tld": "ly",
        "regionId": 4,
        "region": "Middle East",
        "defaultScanCountryId": 40,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3
        ]
    },
    {
        "id": 128,
        "name": "Liechtenstein",
        "defaultLanguageId": 5,
        "code": "li",
        "geonameId": 3042058,
        "tld": "li",
        "regionId": 5,
        "region": "Europe - Non EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            5
        ]
    },
    {
        "id": 34,
        "name": "Lithuania",
        "defaultLanguageId": 34,
        "code": "lt",
        "geonameId": 597427,
        "tld": "lt",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            34
        ]
    },
    {
        "id": 28,
        "name": "Luxembourg",
        "defaultLanguageId": 5,
        "code": "lu",
        "geonameId": 2960313,
        "tld": "lu",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            4,
            5
        ]
    },
    {
        "id": 62,
        "name": "Macedonia",
        "defaultLanguageId": 50,
        "code": "mk",
        "geonameId": 718075,
        "tld": "mk",
        "regionId": 5,
        "region": "Europe - Non EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            50,
            3
        ]
    },
    {
        "id": 56,
        "name": "Malaysia",
        "defaultLanguageId": 58,
        "code": "my",
        "geonameId": 1733045,
        "tld": "my",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            58,
            3
        ]
    },
    {
        "id": 36,
        "name": "Malta",
        "defaultLanguageId": 3,
        "code": "mt",
        "geonameId": 2562770,
        "tld": "mt",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            36,
            3
        ]
    },
    {
        "id": 139,
        "name": "Martinique",
        "defaultLanguageId": 4,
        "code": "mq",
        "geonameId": 3570311,
        "tld": "mq",
        "regionId": 1,
        "region": "North America",
        "defaultScanCountryId": 1,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 143,
        "name": "Mauritius",
        "defaultLanguageId": 2,
        "code": "mu",
        "geonameId": 934292,
        "tld": "mu",
        "regionId": 9,
        "region": "Africa",
        "defaultScanCountryId": 49,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            2
        ]
    },
    {
        "id": 142,
        "name": "Mayotte",
        "defaultLanguageId": 4,
        "code": "yt",
        "geonameId": 1024031,
        "tld": "yt",
        "regionId": 7,
        "region": "Other EU",
        "defaultScanCountryId": 5,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 12,
        "name": "Mexico",
        "defaultLanguageId": 24,
        "code": "mx",
        "geonameId": 3996063,
        "tld": "mx",
        "regionId": 11,
        "region": "Central America",
        "defaultScanCountryId": 12,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            24
        ]
    },
    {
        "id": 101,
        "name": "Moldova",
        "defaultLanguageId": 31,
        "code": "md",
        "geonameId": 617790,
        "tld": "md",
        "regionId": 5,
        "region": "Europe - Non EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            31
        ]
    },
    {
        "id": 102,
        "name": "Morroco",
        "defaultLanguageId": 40,
        "code": "ma",
        "geonameId": 2542007,
        "tld": "ma",
        "regionId": 9,
        "region": "Africa",
        "defaultScanCountryId": 49,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4,
            40
        ]
    },
    {
        "id": 126,
        "name": "Myanmar",
        "defaultLanguageId": 3,
        "code": "mm",
        "geonameId": 1327865,
        "tld": "mm",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3
        ]
    },
    {
        "id": 124,
        "name": "Nepal",
        "defaultLanguageId": 3,
        "code": "np",
        "geonameId": 1282988,
        "tld": "np",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3
        ]
    },
    {
        "id": 8,
        "name": "Netherlands",
        "defaultLanguageId": 1,
        "code": "nl",
        "geonameId": 2750405,
        "tld": "nl",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            1
        ]
    },
    {
        "id": 103,
        "name": "Netherlands Antilles",
        "defaultLanguageId": 3,
        "code": "an",
        "geonameId": 8505032,
        "tld": "an",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7,
            1
        ]
    },
    {
        "id": 48,
        "name": "New Zealand",
        "defaultLanguageId": 2,
        "code": "nz",
        "geonameId": 2186224,
        "tld": "nz",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            2
        ]
    },
    {
        "id": 104,
        "name": "Nicaragua",
        "defaultLanguageId": 3,
        "code": "ni",
        "geonameId": 3617476,
        "tld": "ni",
        "regionId": 11,
        "region": "Central America",
        "defaultScanCountryId": 12,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 53,
        "name": "Nigeria",
        "defaultLanguageId": 3,
        "code": "ng",
        "geonameId": 2328926,
        "tld": "ng",
        "regionId": 9,
        "region": "Africa",
        "defaultScanCountryId": 49,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3
        ]
    },
    {
        "id": 17,
        "name": "Norway",
        "defaultLanguageId": 9,
        "code": "no",
        "geonameId": 3144096,
        "tld": "no",
        "regionId": 5,
        "region": "Europe - Non EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            9
        ]
    },
    {
        "id": 105,
        "name": "Panama",
        "defaultLanguageId": 3,
        "code": "pa",
        "geonameId": 3703430,
        "tld": "pa",
        "regionId": 11,
        "region": "Central America",
        "defaultScanCountryId": 12,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 106,
        "name": "Paraguay",
        "defaultLanguageId": 3,
        "code": "py",
        "geonameId": 3437598,
        "tld": "py",
        "regionId": 6,
        "region": "South America",
        "defaultScanCountryId": 42,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7,
            3
        ]
    },
    {
        "id": 107,
        "name": "Peru",
        "defaultLanguageId": 7,
        "code": "pe",
        "geonameId": 3932488,
        "tld": "pe",
        "regionId": 6,
        "region": "South America",
        "defaultScanCountryId": 42,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7
        ]
    },
    {
        "id": 71,
        "name": "Philippines",
        "defaultLanguageId": 55,
        "code": "ph",
        "geonameId": 1694008,
        "tld": "ph",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            55
        ]
    },
    {
        "id": 18,
        "name": "Poland",
        "defaultLanguageId": 10,
        "code": "pl",
        "geonameId": 798544,
        "tld": "pl",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            10
        ]
    },
    {
        "id": 26,
        "name": "Portugal",
        "defaultLanguageId": 26,
        "code": "pt",
        "geonameId": 2264397,
        "tld": "pt",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            26
        ]
    },
    {
        "id": 108,
        "name": "Puerto Rico",
        "defaultLanguageId": 3,
        "code": "pr",
        "geonameId": 4566966,
        "tld": "pr",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 86,
        "name": "Republic of the Congo",
        "defaultLanguageId": 4,
        "code": "cg",
        "geonameId": 2260494,
        "tld": "cg",
        "regionId": 9,
        "region": "Africa",
        "defaultScanCountryId": 49,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 130,
        "name": "Reunion",
        "defaultLanguageId": 4,
        "code": "re",
        "geonameId": 935317,
        "tld": "re",
        "regionId": 7,
        "region": "Other EU",
        "defaultScanCountryId": 5,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 31,
        "name": "Romania",
        "defaultLanguageId": 31,
        "code": "ro",
        "geonameId": 798549,
        "tld": "ro",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            31
        ]
    },
    {
        "id": 13,
        "name": "Russia",
        "defaultLanguageId": 38,
        "code": "ru",
        "geonameId": 2017370,
        "tld": "ru",
        "regionId": 5,
        "region": "Europe - Non EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            38
        ]
    },
    {
        "id": 109,
        "name": "Saint Kitts & Nevis",
        "defaultLanguageId": 3,
        "code": "kn",
        "geonameId": 3575174,
        "tld": "kn",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7,
            3
        ]
    },
    {
        "id": 111,
        "name": "Saint Lucia",
        "defaultLanguageId": 3,
        "code": "lc",
        "geonameId": 3576468,
        "tld": "lc",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 112,
        "name": "Saint Vincent & Grenadines",
        "defaultLanguageId": 3,
        "code": "vc",
        "geonameId": 3577815,
        "tld": "vc",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 41,
        "name": "Saudi Arabia",
        "defaultLanguageId": 40,
        "code": "sa",
        "geonameId": 102358,
        "tld": "sa",
        "regionId": 4,
        "region": "Middle East",
        "defaultScanCountryId": 40,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            40
        ]
    },
    {
        "id": 110,
        "name": "Senegal",
        "defaultLanguageId": 4,
        "code": "sn",
        "geonameId": 2245662,
        "tld": "sn",
        "regionId": 9,
        "region": "Africa",
        "defaultScanCountryId": 49,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 63,
        "name": "Serbia",
        "defaultLanguageId": 51,
        "code": "rs",
        "geonameId": 6290252,
        "tld": "rs",
        "regionId": 5,
        "region": "Europe - Non EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            51,
            3
        ]
    },
    {
        "id": 60,
        "name": "Singapore",
        "defaultLanguageId": 43,
        "code": "sg",
        "geonameId": 1880251,
        "tld": "sg",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            43,
            3
        ]
    },
    {
        "id": 23,
        "name": "Slovakia",
        "defaultLanguageId": 12,
        "code": "sk",
        "geonameId": 3057568,
        "tld": "sk",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            12
        ]
    },
    {
        "id": 35,
        "name": "Slovenia",
        "defaultLanguageId": 35,
        "code": "si",
        "geonameId": 3190538,
        "tld": "si",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            35
        ]
    },
    {
        "id": 49,
        "name": "South Africa",
        "defaultLanguageId": 3,
        "code": "za",
        "geonameId": 953987,
        "tld": "za",
        "regionId": 9,
        "region": "Africa",
        "defaultScanCountryId": 49,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3
        ]
    },
    {
        "id": 45,
        "name": "South Korea",
        "defaultLanguageId": 45,
        "code": "kr",
        "geonameId": 1835841,
        "tld": "kr",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            45
        ]
    },
    {
        "id": 4,
        "name": "Spain",
        "defaultLanguageId": 7,
        "code": "es",
        "geonameId": 2510769,
        "tld": "es",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            48,
            7
        ]
    },
    {
        "id": 125,
        "name": "Sri Lanka",
        "defaultLanguageId": 3,
        "code": "lk",
        "geonameId": 1227603,
        "tld": "lk",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3
        ]
    },
    {
        "id": 132,
        "name": "St. Barthelemy",
        "defaultLanguageId": 4,
        "code": "bl",
        "geonameId": 3578476,
        "tld": "gg",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 134,
        "name": "St. Martin",
        "defaultLanguageId": 4,
        "code": "mf",
        "geonameId": 3578421,
        "tld": "mf",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 137,
        "name": "St. Pierre and Miquelon",
        "defaultLanguageId": 3,
        "code": "pm",
        "geonameId": 3424932,
        "tld": "pm",
        "regionId": 1,
        "region": "North America",
        "defaultScanCountryId": 1,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    },
    {
        "id": 113,
        "name": "Suriname",
        "defaultLanguageId": 3,
        "code": "sr",
        "geonameId": 3382998,
        "tld": "sr",
        "regionId": 6,
        "region": "South America",
        "defaultScanCountryId": 42,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7,
            1,
            3
        ]
    },
    {
        "id": 22,
        "name": "Sweden",
        "defaultLanguageId": 11,
        "code": "se",
        "geonameId": 2661886,
        "tld": "se",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            11
        ]
    },
    {
        "id": 21,
        "name": "Switzerland",
        "defaultLanguageId": 21,
        "code": "ch",
        "geonameId": 2658434,
        "tld": "ch",
        "regionId": 5,
        "region": "Europe - Non EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            20,
            21,
            6
        ]
    },
    {
        "id": 44,
        "name": "Taiwan",
        "defaultLanguageId": 44,
        "code": "tw",
        "geonameId": 1668284,
        "tld": "tw",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            44
        ]
    },
    {
        "id": 57,
        "name": "Thailand",
        "defaultLanguageId": 56,
        "code": "th",
        "geonameId": 1605651,
        "tld": "th",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            56,
            3
        ]
    },
    {
        "id": 114,
        "name": "Trinidad & Tobago",
        "defaultLanguageId": 3,
        "code": "tt",
        "geonameId": 3573591,
        "tld": "tt",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            7
        ]
    },
    {
        "id": 115,
        "name": "Tunisia",
        "defaultLanguageId": 40,
        "code": "tn",
        "geonameId": 2464461,
        "tld": "tn",
        "regionId": 9,
        "region": "Africa",
        "defaultScanCountryId": 49,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4,
            40
        ]
    },
    {
        "id": 39,
        "name": "Turkey",
        "defaultLanguageId": 39,
        "code": "tr",
        "geonameId": 298795,
        "tld": "tr",
        "regionId": 4,
        "region": "Middle East",
        "defaultScanCountryId": 40,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            39
        ]
    },
    {
        "id": 116,
        "name": "Turks & Caicos Islands",
        "defaultLanguageId": 3,
        "code": "tc",
        "geonameId": 3576916,
        "tld": "tc",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7,
            3
        ]
    },
    {
        "id": 67,
        "name": "Ukraine",
        "defaultLanguageId": 57,
        "code": "ua",
        "geonameId": 690791,
        "tld": "ua",
        "regionId": 5,
        "region": "Europe - Non EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            57
        ]
    },
    {
        "id": 54,
        "name": "United Arab Emirates",
        "defaultLanguageId": 3,
        "code": "ae",
        "geonameId": 290557,
        "tld": "ae",
        "regionId": 4,
        "region": "Middle East",
        "defaultScanCountryId": 40,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            40
        ]
    },
    {
        "id": 6,
        "name": "United Kingdom",
        "defaultLanguageId": 2,
        "code": "gb",
        "geonameId": 2635167,
        "tld": "co.uk",
        "regionId": 2,
        "region": "Europe - EU",
        "defaultScanCountryId": 6,
        "consentTypeId": 2,
        "privacyAccessTypeId": 2,
        "consentRequired": True,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": 13,
        "l2Enabled": True,
        "adChoicesEnabled": False,
        "languages": [
            2
        ]
    },
    {
        "id": 1,
        "name": "United States",
        "defaultLanguageId": 3,
        "code": "us",
        "geonameId": 6252001,
        "tld": "us",
        "regionId": 1,
        "region": "North America",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            24,
            3
        ]
    },
    {
        "id": 117,
        "name": "Uruguay",
        "defaultLanguageId": 3,
        "code": "uy",
        "geonameId": 3439705,
        "tld": "uy",
        "regionId": 6,
        "region": "South America",
        "defaultScanCountryId": 42,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7,
            3
        ]
    },
    {
        "id": 119,
        "name": "Venezuela",
        "defaultLanguageId": 7,
        "code": "ve",
        "geonameId": 3625428,
        "tld": "ve",
        "regionId": 6,
        "region": "South America",
        "defaultScanCountryId": 42,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7
        ]
    },
    {
        "id": 68,
        "name": "Viet Nam",
        "defaultLanguageId": 3,
        "code": "vn",
        "geonameId": 1562822,
        "tld": "vn",
        "regionId": 3,
        "region": "Asia Pacific",
        "defaultScanCountryId": 47,
        "consentTypeId": 1,
        "privacyAccessTypeId": 2,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            3,
            63
        ]
    },
    {
        "id": 118,
        "name": "Virgin Islands, US",
        "defaultLanguageId": 3,
        "code": "vi",
        "geonameId": 4796775,
        "tld": "vi",
        "regionId": 10,
        "region": "Caribbean",
        "defaultScanCountryId": 1,
        "consentTypeId": 1,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            7,
            3
        ]
    },
    {
        "id": 140,
        "name": "Wallis and Futuna",
        "defaultLanguageId": 4,
        "code": "wf",
        "geonameId": 4034749,
        "tld": "wf",
        "regionId": 7,
        "region": "Other EU",
        "defaultScanCountryId": 5,
        "consentTypeId": 2,
        "privacyAccessTypeId": 1,
        "consentRequired": False,
        "regulationConsentTypeId": 0,
        "consentDurationMonths": "null",
        "l2Enabled": False,
        "adChoicesEnabled": False,
        "languages": [
            4
        ]
    }
]